(() => {
  "use strict";

  const translations = {
    "en-US": {
      title: "Easy Cube Games — One creator. Many worlds.",
      description: "Discover Swipe Sprint, Goblin Warcamp, Spellarium and Iron Dominion — indie Android games by Easy Cube Games. Coming soon: Lunisol and Puck Rogue.",
      skip: "Skip to content",
      home: "Easy Cube Games home",
      navigation: "Main navigation",
      language: "Language",
      navGames: "The games",
      eyebrow: "Independent mobile games",
      headlineOne: "One creator.",
      headlineTwo: "Many worlds.",
      intro: "I'm Vasiliy, a solo indie developer. I make games about puzzles, magic, battles and hockey — one idea at a time.",
      visitPlay: "Visit Google Play",
      explore: "Explore the games",
      worldsAlt: "A knight, a fire-and-water crystal and colorful puzzle tiles surround the Easy Cube Games logo.",
      gamesTitle: "Find your kind of play.",
      android: "Made for Android",
      updated: "Updated",
      newRelease: "New release",
      availableNow: "Available now",
      inDevelopment: "Coming soon",
      spellGenre: "Idle · Magic · Crafting",
      spellSubtitle: "Magic Clicker",
      spellDescription: "Gather essence, craft spells and unlock fire and water. Build your magical workshop, one tap at a time.",
      spellLink: "Get Spellarium: Magic Clicker on Google Play",
      getPlay: "Get it on Google Play",
      ironGenre: "Match-3 · Strategy · Roguelite",
      ironSubtitle: "Match 3 RPG",
      ironDescription: "Match tiles to summon an army. Choose your route, recruit champions and shape each roguelite run.",
      ironLink: "Get Iron Dominion: Match 3 RPG on Google Play",
      comingSoon: "Coming soon to Google Play",
      swipeGenre: "Reaction · Shapes · Speed",
      swipeSubtitle: "Reaction Game",
      swipeDescription: "Spot the shape and swipe its tiles before time runs out. Take on 100 levels with decoys, rotations and memory challenges, then keep going in endless mode.",
      swipeLink: "Get Swipe Sprint: Reaction Game on Google Play",
      goblinGenre: "Strategy · Merging · Auto battles",
      goblinDescription: "Build a goblin camp on a hex board. Merge buildings, boost neighboring troops and send your army into automatic battles on the road to 12 victories.",
      goblinLink: "Get Goblin Warcamp on Google Play",
      lunisolGenre: "Logic · Suns & moons · Relaxation",
      lunisolSubtitle: "Binary Logic Puzzle",
      lunisolDescription: "Bring suns and moons into balance on a 6×6 grid. Solve 150 puzzles with hints that explain each step, then discover endless new grids.",
      puckGenre: "Hockey · Tactics · Roguelike",
      puckSubtitle: "Ice Hockey Manager",
      puckDescription: "Coach a hockey team through a roguelike cup run. Set your lines, choose tactics and strengthen players with cards while the matches play out on the ice.",
      footer: "Made with care. Played your way.",
      contact: "Say hello",
      artCaption: ["PUZZLES", "MAGIC", "BATTLES"]
    },
    "ru-RU": {
      title: "Easy Cube Games — Один автор. Много миров.",
      description: "Swipe Sprint, Goblin Warcamp, Spellarium и Iron Dominion — игры для Android от Easy Cube Games. Скоро: Lunisol и Puck Rogue.",
      skip: "Перейти к содержимому",
      home: "Easy Cube Games — главная",
      navigation: "Основная навигация",
      language: "Язык",
      navGames: "Игры",
      eyebrow: "Независимые мобильные игры",
      headlineOne: "Один автор.",
      headlineTwo: "Много миров.",
      intro: "Я Василий, независимый разработчик. Создаю игры про головоломки, магию, сражения и хоккей — воплощая идеи одну за другой.",
      visitPlay: "Открыть Google Play",
      explore: "Посмотреть игры",
      worldsAlt: "Рыцарь, кристалл огня и воды и цветные элементы головоломки вокруг логотипа Easy Cube Games.",
      gamesTitle: "Найдите свою игру.",
      android: "Созданы для Android",
      updated: "Обновлено",
      newRelease: "Новая игра",
      availableNow: "Уже доступно",
      inDevelopment: "Скоро",
      spellGenre: "Кликер · Магия · Крафт",
      spellSubtitle: "Магический кликер",
      spellDescription: "Собирайте эссенцию, создавайте заклинания и открывайте огонь и воду. Развивайте магическую мастерскую с каждым тапом.",
      spellLink: "Открыть Spellarium: Магический кликер в Google Play",
      getPlay: "Скачать в Google Play",
      ironGenre: "Три в ряд · Стратегия · Roguelite",
      ironSubtitle: "Три в ряд RPG",
      ironDescription: "Собирайте комбинации, чтобы призвать армию. Выбирайте маршрут, набирайте героев и пробуйте новую тактику в каждом походе.",
      ironLink: "Открыть Iron Dominion: Три в ряд RPG в Google Play",
      comingSoon: "Скоро в Google Play",
      swipeGenre: "Реакция · Фигуры · Скорость",
      swipeSubtitle: "Игра на реакцию",
      swipeDescription: "Найдите фигуру и проведите по её плиткам, пока не вышло время. Пройдите 100 уровней с обманками, поворотами и заданиями на память, а затем играйте бесконечно.",
      swipeLink: "Открыть Swipe Sprint: игра на реакцию в Google Play",
      goblinGenre: "Стратегия · Слияние · Автобои",
      goblinDescription: "Стройте лагерь гоблинов на гексах. Объединяйте здания, усиливайте соседние отряды и отправляйте армию в автоматические бои на пути к 12 победам.",
      goblinLink: "Открыть Goblin Warcamp в Google Play",
      lunisolGenre: "Логика · Солнца и луны · Отдых",
      lunisolSubtitle: "Логическая головоломка",
      lunisolDescription: "Найдите баланс солнц и лун на поле 6×6. Решите 150 головоломок с подсказками, которые объясняют каждый шаг, а затем открывайте бесконечные новые поля.",
      puckGenre: "Хоккей · Тактика · Рогалик",
      puckSubtitle: "Хоккейный менеджер",
      puckDescription: "Ведите хоккейную команду к кубку в забеге-рогалике. Собирайте звенья, выбирайте тактику и усиливайте игроков картами, пока на льду идут автоматические матчи.",
      footer: "Создаю с душой. Играйте в удовольствие.",
      contact: "Написать мне",
      artCaption: ["ГОЛОВОЛОМКИ", "МАГИЯ", "СРАЖЕНИЯ"]
    },
    "de-DE": {
      title: "Easy Cube Games — Ein Entwickler. Viele Welten.",
      description: "Entdecke Swipe Sprint, Goblin Warcamp, Spellarium und Iron Dominion — Indie-Spiele für Android von Easy Cube Games. Bald: Lunisol und Puck Rogue.",
      skip: "Zum Inhalt springen",
      home: "Easy Cube Games — Startseite",
      navigation: "Hauptnavigation",
      language: "Sprache",
      navGames: "Die Spiele",
      eyebrow: "Unabhängige Handyspiele",
      headlineOne: "Ein Entwickler.",
      headlineTwo: "Viele Welten.",
      intro: "Ich bin Vasiliy, ein unabhängiger Spieleentwickler. Ich entwickle Spiele voller Rätsel, Magie, Kämpfe und Eishockey — eine Idee nach der anderen.",
      visitPlay: "Zu Google Play",
      explore: "Spiele entdecken",
      worldsAlt: "Ein Ritter, ein Kristall aus Feuer und Wasser und bunte Puzzlesteine umgeben das Logo von Easy Cube Games.",
      gamesTitle: "Finde dein Spiel.",
      android: "Für Android entwickelt",
      updated: "Aktualisiert",
      newRelease: "Neu erschienen",
      availableNow: "Jetzt verfügbar",
      inDevelopment: "Demnächst",
      spellGenre: "Idle · Magie · Zauberkunst",
      spellSubtitle: "Magischer Clicker",
      spellDescription: "Sammle Essenz, erschaffe Zauber und entdecke Feuer und Wasser. Baue deine magische Werkstatt auf — mit jedem Tippen ein Stück weiter.",
      spellLink: "Spellarium: Magischer Clicker bei Google Play herunterladen",
      getPlay: "Bei Google Play herunterladen",
      ironGenre: "Match-3 · Strategie · Roguelite",
      ironSubtitle: "Match-3-RPG",
      ironDescription: "Kombiniere Spielsteine, um eine Armee zu beschwören. Wähle deinen Weg, rekrutiere Helden und gestalte jeden Roguelite-Durchlauf neu.",
      ironLink: "Iron Dominion: Match-3-RPG bei Google Play herunterladen",
      comingSoon: "Bald bei Google Play",
      swipeGenre: "Reaktion · Formen · Tempo",
      swipeSubtitle: "Reaktionsspiel",
      swipeDescription: "Erkenne die Form und wische über ihre Felder, bevor die Zeit abläuft. Meistere 100 Level mit Ablenkungen, Drehungen und Gedächtnisaufgaben. Danach geht es im Endlosmodus weiter.",
      swipeLink: "Swipe Sprint: Reaktionsspiel bei Google Play herunterladen",
      goblinGenre: "Strategie · Fusionen · Autokämpfe",
      goblinDescription: "Baue ein Goblinlager auf einem Hexfeld. Verschmelze Gebäude, verstärke benachbarte Truppen und schicke deine Armee in automatische Kämpfe auf dem Weg zu 12 Siegen.",
      goblinLink: "Goblin Warcamp bei Google Play herunterladen",
      lunisolGenre: "Logik · Sonne und Mond · Entspannung",
      lunisolSubtitle: "Logikrätsel",
      lunisolDescription: "Bringe Sonnen und Monde auf einem 6×6-Raster ins Gleichgewicht. Löse 150 Rätsel mit Hinweisen, die jeden Schritt erklären. Danach warten endlos neue Rätsel.",
      puckGenre: "Eishockey · Taktik · Roguelike",
      puckSubtitle: "Eishockey-Manager",
      puckDescription: "Führe ein Eishockeyteam in einem Roguelike-Durchlauf zum Pokal. Stelle deine Reihen auf, wähle Taktiken und verstärke Spieler mit Karten, während die Spiele auf dem Eis automatisch ablaufen.",
      footer: "Mit Sorgfalt entwickelt. Für deinen Spielstil.",
      contact: "Schreib mir",
      artCaption: ["RÄTSEL", "MAGIE", "KÄMPFE"]
    },
    "fr-FR": {
      title: "Easy Cube Games — Un créateur. De nombreux mondes.",
      description: "Découvrez Swipe Sprint, Goblin Warcamp, Spellarium et Iron Dominion, les jeux Android indépendants d’Easy Cube Games. Bientôt : Lunisol et Puck Rogue.",
      skip: "Aller au contenu",
      home: "Easy Cube Games — Accueil",
      navigation: "Navigation principale",
      language: "Langue",
      navGames: "Les jeux",
      eyebrow: "Jeux mobiles indépendants",
      headlineOne: "Un créateur.",
      headlineTwo: "De nombreux mondes.",
      intro: "Je m’appelle Vasiliy et je crée des jeux en solo. Énigmes, magie, batailles et hockey : je donne vie à mes idées, une à la fois.",
      visitPlay: "Voir sur Google Play",
      explore: "Découvrir les jeux",
      worldsAlt: "Un chevalier, un cristal de feu et d’eau et des pièces de puzzle colorées entourent le logo d’Easy Cube Games.",
      gamesTitle: "Trouvez votre jeu.",
      android: "Conçus pour Android",
      updated: "Mis à jour",
      newRelease: "Nouveauté",
      availableNow: "Disponible",
      inDevelopment: "Bientôt",
      spellGenre: "Incrémental · Magie · Création",
      spellSubtitle: "Clicker magique",
      spellDescription: "Récoltez de l’essence, créez des sorts et découvrez le feu et l’eau. Développez votre atelier magique, une touche à la fois.",
      spellLink: "Télécharger Spellarium : Clicker magique sur Google Play",
      getPlay: "Télécharger sur Google Play",
      ironGenre: "Match-3 · Stratégie · Roguelite",
      ironSubtitle: "RPG Match-3",
      ironDescription: "Alignez des tuiles pour invoquer une armée. Choisissez votre chemin, recrutez des champions et façonnez chaque aventure roguelite.",
      ironLink: "Télécharger Iron Dominion : RPG Match-3 sur Google Play",
      comingSoon: "Bientôt sur Google Play",
      swipeGenre: "Réflexes · Formes · Rapidité",
      swipeSubtitle: "Jeu de réflexe",
      swipeDescription: "Repérez la forme et balayez ses cases avant la fin du temps imparti. Relevez 100 niveaux avec des leurres, des rotations et des défis de mémoire, puis passez au mode infini.",
      swipeLink: "Télécharger Swipe Sprint : Jeu de réflexe sur Google Play",
      goblinGenre: "Stratégie · Fusion · Combats auto",
      goblinDescription: "Bâtissez un camp de gobelins sur des cases hexagonales. Fusionnez les bâtiments, renforcez les troupes voisines et lancez votre armée dans des combats automatiques pour atteindre 12 victoires.",
      goblinLink: "Télécharger Goblin Warcamp sur Google Play",
      lunisolGenre: "Logique · Soleils et lunes · Détente",
      lunisolSubtitle: "Sudoku binaire",
      lunisolDescription: "Équilibrez les soleils et les lunes sur une grille de 6×6. Résolvez 150 énigmes avec des indices qui expliquent chaque étape, puis découvrez de nouvelles grilles à l’infini.",
      puckGenre: "Hockey · Tactique · Roguelike",
      puckSubtitle: "Manager de hockey sur glace",
      puckDescription: "Menez une équipe de hockey vers la coupe dans une aventure roguelike. Composez vos lignes, choisissez vos tactiques et renforcez les joueurs avec des cartes pendant que les matchs se jouent automatiquement.",
      footer: "Des jeux créés avec soin. À vous de jouer.",
      contact: "Écrivez-moi",
      artCaption: ["ÉNIGMES", "MAGIE", "BATAILLES"]
    },
    "es-ES": {
      title: "Easy Cube Games — Un creador. Muchos mundos.",
      description: "Descubre Swipe Sprint, Goblin Warcamp, Spellarium e Iron Dominion, juegos independientes para Android de Easy Cube Games. Próximamente: Lunisol y Puck Rogue.",
      skip: "Saltar al contenido",
      home: "Easy Cube Games — Inicio",
      navigation: "Navegación principal",
      language: "Idioma",
      navGames: "Los juegos",
      eyebrow: "Juegos móviles independientes",
      headlineOne: "Un creador.",
      headlineTwo: "Muchos mundos.",
      intro: "Soy Vasiliy, un desarrollador independiente que trabaja en solitario. Creo juegos de puzles, magia, batallas y hockey, una idea cada vez.",
      visitPlay: "Visitar Google Play",
      explore: "Descubrir los juegos",
      worldsAlt: "Un caballero, un cristal de fuego y agua y piezas de puzle de colores rodean el logotipo de Easy Cube Games.",
      gamesTitle: "Encuentra tu juego.",
      android: "Creados para Android",
      updated: "Actualizado",
      newRelease: "Nuevo juego",
      availableNow: "Ya disponible",
      inDevelopment: "Próximamente",
      spellGenre: "Incremental · Magia · Creación",
      spellSubtitle: "Clicker mágico",
      spellDescription: "Recoge esencia, crea hechizos y descubre el fuego y el agua. Desarrolla tu taller mágico, toque a toque.",
      spellLink: "Descargar Spellarium: Clicker mágico en Google Play",
      getPlay: "Descargar en Google Play",
      ironGenre: "Combina 3 · Estrategia · Roguelite",
      ironSubtitle: "RPG de combinar 3",
      ironDescription: "Combina fichas para invocar un ejército. Elige tu ruta, recluta campeones y da forma a cada aventura roguelite.",
      ironLink: "Descargar Iron Dominion: RPG de combinar 3 en Google Play",
      comingSoon: "Próximamente en Google Play",
      swipeGenre: "Reflejos · Formas · Velocidad",
      swipeSubtitle: "Reflejos rápidos",
      swipeDescription: "Encuentra la figura y desliza el dedo por sus casillas antes de que se acabe el tiempo. Supera 100 niveles con señuelos, giros y retos de memoria, y sigue jugando en el modo infinito.",
      swipeLink: "Descargar Swipe Sprint: Reflejos rápidos en Google Play",
      goblinGenre: "Estrategia · Fusión · Batallas auto",
      goblinDescription: "Construye un campamento de goblins en un tablero hexagonal. Fusiona edificios, refuerza las tropas vecinas y envía a tu ejército a batallas automáticas para alcanzar 12 victorias.",
      goblinLink: "Descargar Goblin Warcamp en Google Play",
      lunisolGenre: "Lógica · Soles y lunas · Relax",
      lunisolSubtitle: "Puzle de lógica binaria",
      lunisolDescription: "Equilibra soles y lunas en una cuadrícula de 6×6. Resuelve 150 puzles con pistas que explican cada paso y descubre después nuevas cuadrículas sin fin.",
      puckGenre: "Hockey · Táctica · Roguelike",
      puckSubtitle: "Mánager de hockey sobre hielo",
      puckDescription: "Lleva a un equipo de hockey hasta la copa en una aventura roguelike. Forma tus líneas, elige la táctica y mejora a tus jugadores con cartas mientras los partidos se juegan solos.",
      footer: "Hechos con cariño. Juega a tu manera.",
      contact: "Escríbeme",
      artCaption: ["PUZLES", "MAGIA", "BATALLAS"]
    },
    "pt-BR": {
      title: "Easy Cube Games — Um criador. Muitos mundos.",
      description: "Conheça Swipe Sprint, Goblin Warcamp, Spellarium e Iron Dominion, jogos independentes para Android da Easy Cube Games. Em breve: Lunisol e Puck Rogue.",
      skip: "Ir para o conteúdo",
      home: "Easy Cube Games — Início",
      navigation: "Navegação principal",
      language: "Idioma",
      navGames: "Os jogos",
      eyebrow: "Jogos independentes para celular",
      headlineOne: "Um criador.",
      headlineTwo: "Muitos mundos.",
      intro: "Sou Vasiliy, um desenvolvedor independente que trabalha sozinho. Crio jogos de quebra-cabeças, magia, batalhas e hóquei, uma ideia de cada vez.",
      visitPlay: "Visitar o Google Play",
      explore: "Conhecer os jogos",
      worldsAlt: "Um cavaleiro, um cristal de fogo e água e peças coloridas de quebra-cabeça cercam o logotipo da Easy Cube Games.",
      gamesTitle: "Encontre seu jogo.",
      android: "Feitos para Android",
      updated: "Atualizado",
      newRelease: "Lançamento",
      availableNow: "Já disponível",
      inDevelopment: "Em breve",
      spellGenre: "Incremental · Magia · Criação",
      spellSubtitle: "Clicker mágico",
      spellDescription: "Colete essência, crie feitiços e descubra o fogo e a água. Desenvolva sua oficina mágica, um toque de cada vez.",
      spellLink: "Baixar Spellarium: Clicker mágico no Google Play",
      getPlay: "Baixar no Google Play",
      ironGenre: "Combine 3 · Estratégia · Roguelite",
      ironSubtitle: "RPG de combinar 3",
      ironDescription: "Combine peças para invocar um exército. Escolha seu caminho, recrute campeões e dê forma a cada jornada roguelite.",
      ironLink: "Baixar Iron Dominion: RPG de combinar 3 no Google Play",
      comingSoon: "Em breve no Google Play",
      swipeGenre: "Reflexos · Formas · Velocidade",
      swipeSubtitle: "Jogo de reflexo",
      swipeDescription: "Encontre a figura e deslize o dedo pelas peças antes que o tempo acabe. Encare 100 fases com distrações, rotações e desafios de memória, depois continue no modo infinito.",
      swipeLink: "Baixar Swipe Sprint: Jogo de reflexo no Google Play",
      goblinGenre: "Estratégia · Fusão · Batalhas auto",
      goblinDescription: "Construa um acampamento de goblins num tabuleiro hexagonal. Una construções, fortaleça as tropas vizinhas e envie seu exército para batalhas automáticas rumo a 12 vitórias.",
      goblinLink: "Baixar Goblin Warcamp no Google Play",
      lunisolGenre: "Lógica · Sóis e luas · Relaxamento",
      lunisolSubtitle: "Quebra-cabeça lógico",
      lunisolDescription: "Equilibre sóis e luas numa grade de 6×6. Resolva 150 quebra-cabeças com dicas que explicam cada passo e descubra depois novas grades sem fim.",
      puckGenre: "Hóquei · Tática · Roguelike",
      puckSubtitle: "Manager de hóquei no gelo",
      puckDescription: "Leve um time de hóquei até a copa numa jornada roguelike. Monte suas linhas, escolha a tática e fortaleça os jogadores com cartas enquanto as partidas acontecem sozinhas.",
      footer: "Feitos com carinho. Jogue do seu jeito.",
      contact: "Fale comigo",
      artCaption: ["QUEBRA-CABEÇAS", "MAGIA", "BATALHAS"]
    },
    "it-IT": {
      title: "Easy Cube Games — Un autore. Tanti mondi.",
      description: "Scopri Swipe Sprint, Goblin Warcamp, Spellarium e Iron Dominion, i giochi indie per Android di Easy Cube Games. In arrivo: Lunisol e Puck Rogue.",
      skip: "Vai al contenuto",
      home: "Easy Cube Games — Pagina iniziale",
      navigation: "Navigazione principale",
      language: "Lingua",
      navGames: "I giochi",
      eyebrow: "Giochi mobile indipendenti",
      headlineOne: "Un autore.",
      headlineTwo: "Tanti mondi.",
      intro: "Sono Vasiliy, uno sviluppatore indipendente che lavora da solo. Creo giochi di rompicapi, magia, battaglie e hockey, un’idea alla volta.",
      visitPlay: "Vai su Google Play",
      explore: "Scopri i giochi",
      worldsAlt: "Un cavaliere, un cristallo di fuoco e acqua e tessere colorate circondano il logo di Easy Cube Games.",
      gamesTitle: "Trova il tuo gioco.",
      android: "Creati per Android",
      updated: "Aggiornato",
      newRelease: "Nuova uscita",
      availableNow: "Già disponibile",
      inDevelopment: "In arrivo",
      spellGenre: "Incrementale · Magia · Creazione",
      spellSubtitle: "Clicker magico",
      spellDescription: "Raccogli essenza, crea incantesimi e scopri il fuoco e l’acqua. Fai crescere il tuo laboratorio magico, un tocco alla volta.",
      spellLink: "Scarica Spellarium: Clicker magico su Google Play",
      getPlay: "Scarica su Google Play",
      ironGenre: "Match-3 · Strategia · Roguelite",
      ironSubtitle: "GDR match-3",
      ironDescription: "Abbina le tessere per evocare un esercito. Scegli il percorso, recluta campioni e dai forma a ogni avventura roguelite.",
      ironLink: "Scarica Iron Dominion: GDR match-3 su Google Play",
      comingSoon: "Presto su Google Play",
      swipeGenre: "Riflessi · Forme · Velocità",
      swipeSubtitle: "Gioco di riflessi",
      swipeDescription: "Trova la figura e scorri sulle sue caselle prima che scada il tempo. Affronta 100 livelli con distrazioni, rotazioni e sfide di memoria, poi continua nella modalità infinita.",
      swipeLink: "Scarica Swipe Sprint: Gioco di riflessi su Google Play",
      goblinGenre: "Strategia · Fusioni · Battaglie auto",
      goblinDescription: "Costruisci un accampamento di goblin su una griglia esagonale. Unisci gli edifici, potenzia le truppe vicine e manda il tuo esercito in battaglie automatiche verso 12 vittorie.",
      goblinLink: "Scarica Goblin Warcamp su Google Play",
      lunisolGenre: "Logica · Soli e lune · Relax",
      lunisolSubtitle: "Rompicapo di logica binaria",
      lunisolDescription: "Bilancia soli e lune su una griglia 6×6. Risolvi 150 rompicapi con suggerimenti che spiegano ogni passaggio, poi scopri nuove griglie senza fine.",
      puckGenre: "Hockey · Tattica · Roguelike",
      puckSubtitle: "Manager di hockey su ghiaccio",
      puckDescription: "Guida una squadra di hockey alla coppa in un’avventura roguelike. Componi le linee, scegli la tattica e potenzia i giocatori con le carte mentre le partite si svolgono da sole.",
      footer: "Creati con cura. Gioca a modo tuo.",
      contact: "Scrivimi",
      artCaption: ["ROMPICAPI", "MAGIA", "BATTAGLIE"]
    },
    "pl-PL": {
      title: "Easy Cube Games — Jeden twórca. Wiele światów.",
      description: "Poznaj Swipe Sprint, Goblin Warcamp, Spellarium i Iron Dominion — niezależne gry na Androida od Easy Cube Games. Wkrótce: Lunisol i Puck Rogue.",
      skip: "Przejdź do treści",
      home: "Easy Cube Games — strona główna",
      navigation: "Nawigacja główna",
      language: "Język",
      navGames: "Gry",
      eyebrow: "Niezależne gry mobilne",
      headlineOne: "Jeden twórca.",
      headlineTwo: "Wiele światów.",
      intro: "Mam na imię Vasiliy i samodzielnie tworzę gry. Łamigłówki, magia, bitwy i hokej — wcielam pomysły w życie, jeden po drugim.",
      visitPlay: "Odwiedź Google Play",
      explore: "Poznaj gry",
      worldsAlt: "Rycerz, kryształ ognia i wody oraz kolorowe elementy łamigłówki otaczają logo Easy Cube Games.",
      gamesTitle: "Znajdź swoją grę.",
      android: "Stworzone na Androida",
      updated: "Aktualizacja",
      newRelease: "Nowa gra",
      availableNow: "Już dostępne",
      inDevelopment: "Wkrótce",
      spellGenre: "Klikanie · Magia · Tworzenie",
      spellSubtitle: "Magiczny kliker",
      spellDescription: "Zbieraj esencję, twórz zaklęcia i odkrywaj ogień oraz wodę. Rozwijaj swój magiczny warsztat, krok po kroku, dotknięcie po dotknięciu.",
      spellLink: "Pobierz Spellarium: Magiczny kliker z Google Play",
      getPlay: "Pobierz z Google Play",
      ironGenre: "Dopasuj 3 · Strategia · Roguelite",
      ironSubtitle: "RPG z dopasowywaniem 3",
      ironDescription: "Dopasowuj kafelki, by przywołać armię. Wybieraj trasę, rekrutuj bohaterów i kształtuj każdą wyprawę roguelite.",
      ironLink: "Pobierz Iron Dominion: RPG z dopasowywaniem 3 z Google Play",
      comingSoon: "Wkrótce w Google Play",
      swipeGenre: "Refleks · Kształty · Szybkość",
      swipeSubtitle: "Gra na refleks",
      swipeDescription: "Znajdź kształt i przesuń palcem po jego polach, zanim skończy się czas. Pokonaj 100 poziomów ze zmyłkami, obrotami i zadaniami pamięciowymi, a potem graj w trybie bez końca.",
      swipeLink: "Pobierz Swipe Sprint: Gra na refleks z Google Play",
      goblinGenre: "Strategia · Łączenie · Bitwy",
      goblinDescription: "Zbuduj obóz goblinów na heksagonalnej planszy. Łącz budynki, wzmacniaj sąsiednie oddziały i wysyłaj armię do automatycznych bitew na drodze do 12 zwycięstw.",
      goblinLink: "Pobierz Goblin Warcamp z Google Play",
      lunisolGenre: "Logika · Słońca i księżyce · Relaks",
      lunisolSubtitle: "Łamigłówka logiczna",
      lunisolDescription: "Zrównoważ słońca i księżyce na planszy 6×6. Rozwiąż 150 łamigłówek ze wskazówkami wyjaśniającymi każdy krok, a potem odkrywaj kolejne plansze bez końca.",
      puckGenre: "Hokej · Taktyka · Roguelike",
      puckSubtitle: "Menedżer hokeja na lodzie",
      puckDescription: "Poprowadź drużynę hokejową po puchar w wyprawie roguelike. Ustawiaj formacje, wybieraj taktykę i wzmacniaj zawodników kartami, a mecze rozegrają się automatycznie.",
      footer: "Tworzone z sercem. Graj po swojemu.",
      contact: "Napisz do mnie",
      artCaption: ["ŁAMIGŁÓWKI", "MAGIA", "BITWY"]
    },
    "tr-TR": {
      title: "Easy Cube Games — Tek geliştirici. Pek çok dünya.",
      description: "Easy Cube Games’in bağımsız Android oyunlarını keşfet: Swipe Sprint, Goblin Warcamp, Spellarium ve Iron Dominion. Yakında: Lunisol ve Puck Rogue.",
      skip: "İçeriğe geç",
      home: "Easy Cube Games ana sayfası",
      navigation: "Ana gezinme",
      language: "Dil",
      navGames: "Oyunlar",
      eyebrow: "Bağımsız mobil oyunlar",
      headlineOne: "Tek geliştirici.",
      headlineTwo: "Pek çok dünya.",
      intro: "Ben Vasiliy, tek başına çalışan bağımsız bir oyun geliştiricisiyim. Bulmaca, büyü, savaş ve hokey oyunları yapıyor, fikirlerimi birer birer hayata geçiriyorum.",
      visitPlay: "Google Play’e git",
      explore: "Oyunları keşfet",
      worldsAlt: "Bir şövalye, ateş ve su kristali ve renkli bulmaca taşları Easy Cube Games logosunu çevreliyor.",
      gamesTitle: "Sana göre bir oyun bul.",
      android: "Android için geliştirildi",
      updated: "Güncellendi",
      newRelease: "Yeni oyun",
      availableNow: "Şimdi yayında",
      inDevelopment: "Yakında",
      spellGenre: "Tıklama · Büyü · Üretim",
      spellSubtitle: "Büyülü tıklama oyunu",
      spellDescription: "Öz topla, büyüler üret, ateşi ve suyu keşfet. Her dokunuşla büyü atölyeni biraz daha geliştir.",
      spellLink: "Spellarium: Büyülü tıklama oyununu Google Play’den indir",
      getPlay: "Google Play’den indir",
      ironGenre: "3 eşleştir · Strateji · Roguelite",
      ironSubtitle: "3 eşleştirmeli RYO",
      ironDescription: "Taşları eşleştirerek bir ordu çağır. Rotanı seç, şampiyonlar topla ve her roguelite maceranı kendi kararlarınla şekillendir.",
      ironLink: "Iron Dominion: 3 eşleştirmeli RYO’yu Google Play’den indir",
      comingSoon: "Yakında Google Play’de",
      swipeGenre: "Refleks · Şekiller · Hız",
      swipeSubtitle: "Refleks Oyunu",
      swipeDescription: "Süre dolmadan şekli bul ve parmağını karelerinin üzerinden kaydır. Yanıltıcı kareler, döndürülmüş şekiller ve hafıza görevleriyle dolu 100 bölümü tamamla, ardından sonsuz modda devam et.",
      swipeLink: "Swipe Sprint: Refleks Oyunu’nu Google Play’den indir",
      goblinGenre: "Strateji · Birleştirme · Otomatik savaş",
      goblinDescription: "Altıgen bir alanda goblin kampı kur. Binaları birleştir, komşu birlikleri güçlendir ve 12 zafere ulaşmak için ordunu otomatik savaşlara gönder.",
      goblinLink: "Goblin Warcamp’i Google Play’den indir",
      lunisolGenre: "Mantık · Güneş ve ay · Rahatlama",
      lunisolSubtitle: "Mantık Bulmacası",
      lunisolDescription: "6×6’lık bir tabloda güneşlerle ayları dengele. Her adımı açıklayan ipuçlarıyla 150 bulmacayı çöz, ardından sınırsız yeni tabloları keşfet.",
      puckGenre: "Buz hokeyi · Taktik · Roguelike",
      puckSubtitle: "Buz hokeyi menajeri",
      puckDescription: "Bir hokey takımını roguelike macerasında kupaya taşı. Beşlilerini kur, taktiklerini seç ve maçlar buzda otomatik oynanırken oyuncularını kartlarla güçlendir.",
      footer: "Özenle geliştirildi. Kendi tarzında oyna.",
      contact: "Bana yaz",
      artCaption: ["BULMACALAR", "BÜYÜ", "SAVAŞLAR"]
    }
  };

  const languageSelect = document.querySelector("#language-select");
  const storageKey = "easycube.language";
  const supportedLanguages = Object.keys(translations);

  function resolveLanguage(language) {
    if (typeof language !== "string") return undefined;
    const normalized = language.toLowerCase();
    return supportedLanguages.find(locale => locale.toLowerCase() === normalized)
      || supportedLanguages.find(locale => locale.split("-")[0] === normalized.split("-")[0]);
  }

  function preferredLanguage() {
    try {
      const saved = resolveLanguage(localStorage.getItem(storageKey));
      if (saved) return saved;
    } catch {
      // Browser privacy settings can disable storage; language selection still works.
    }
    const browserLanguages = navigator.languages?.length ? navigator.languages : [navigator.language];
    return browserLanguages.map(resolveLanguage).find(Boolean) || "en-US";
  }

  function setLanguage(language) {
    const copy = translations[language];
    if (!copy) return;
    document.documentElement.lang = language;
    document.title = copy.title;
    document.querySelector('meta[name="description"]').content = copy.description;
    document.querySelectorAll("[data-i18n]").forEach(element => {
      element.textContent = copy[element.dataset.i18n];
    });
    document.querySelectorAll("[data-i18n-aria]").forEach(element => {
      element.setAttribute("aria-label", copy[element.dataset.i18nAria]);
    });
    document.querySelectorAll("[data-i18n-alt]").forEach(element => {
      element.alt = copy[element.dataset.i18nAlt];
    });
    languageSelect.value = language;
    document.querySelectorAll(".art-caption span").forEach((element, index) => {
      element.textContent = copy.artCaption[index];
    });
  }

  languageSelect.addEventListener("change", () => {
    setLanguage(languageSelect.value);
    try {
      localStorage.setItem(storageKey, languageSelect.value);
    } catch {
      // Keep the selected language for this visit even when it cannot be saved.
    }
  });

  setLanguage(preferredLanguage());
  languageSelect.disabled = false;
})();
